# Generated by Django 3.2.7 on 2021-10-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='in_sck',
            new_name='in_stock',
        ),
    ]
